<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Responses List PDF</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            color: #333;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .header h2 {
            margin: 0;
        }
        .details {
            margin-bottom: 20px;
        }
        .details p {
            margin: 5px 0;
        }
        .details h4 {
            margin-bottom: 10px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 5px;
        }
        .footer {
            text-align: center;
            font-size: 12px;
            margin-top: 30px;
        }
        .section {
            margin-bottom: 15px;
        }
        .response-item {
            margin-bottom: 30px;
            border-bottom: 1px solid #ddd;
            padding-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h2>Responses List</h2>
    </div>

    @foreach ($responses as $response)
        <div class="response-item">
            <div class="details">
                <div class="section">
                    <h4>Courrier Reference:</h4>
                    <p>{{ $response->courrier->reference }}</p>
                </div>
                <div class="section">
                    <h4>Created By:</h4>
                    <p>{{ $response->creator->name }}</p>
                </div>
                <div class="section">
                    <h4>Content:</h4>
                    <p>{{ $response->content }}</p>
                </div>
                <div class="section">
                    <h4>Created At:</h4>
                    <p>{{ $response->created_at->format('d-m-Y H:i') }}</p>
                </div>
            </div>
        </div>
    @endforeach

    <div class="footer">
        <p>Generated by {{ config('app.name') }} on {{ \Carbon\Carbon::now()->format('d-m-Y H:i') }}</p>
    </div>
</body>
</html>
